import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/shared/Navbar/Navbar";
import { Footer } from "@/components/shared/Footer/Footer";
import { Toaster } from "sonner";
import { getCurrentUser } from "./(auth)/_action/getCurrentUser";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Fixit now",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode}>) {
  const user = await getCurrentUser();

  console.log(user);

  return (
  <html
    lang="en"
    className={cn("h-full", "antialiased", "font-sans", inter.variable)}>
    <body className="min-h-full flex flex-col">
      <>
        <Navbar user={user}/>
          <Toaster />
          <main>
            {children}
          </main>
        <Footer />
      </>
    </body>
  </html>
  );
}
